spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
          - id: changgou_goods_route
            #uri: http://localhost:18081
            uri: lb://goods   #所有的请求都提交给goods服务器
            predicates:
              #- Host=cloud.itheima.com**
              #- Path=/api/brand**
              - Path=/api/album/**,/api/brand/**,/api/cache/**,/api/categoryBrand/**,/api/category/**,/api/para/**,/api/pref/**,/api/sku/**,/api/spec/**,/api/spu/**,/api/stockBack/**,/api/template/**
            filters:
             # - PrefixPath=/brand
              - StripPrefix=1   #会将请求路劲中的第一个路径过滤
              - name: RequestRateLimiter #请求数限流 名字不能随便写，使用默认的facatory
                args:
                  key-resolver: "#{@ipKeyResolver}"
                  redis-rate-limiter.replenishRate: 1
                  redis-rate-limiter.burstCapacity: 1
                    #用户微服务
          - id: changgou_user_auth
            uri: lb://user-auth
            predicates:
            - Path=/api/user/**
            filters:
            - StripPrefix=1

              #用户微服务
          - id: changgou_user_route
            uri: lb://user
            predicates:
              - Path=/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
            filters:
              - StripPrefix=1

            #订单微服务
          - id: changgou_order_route
            uri: lb://order
            predicates:
            - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
            filters:
            - StripPrefix=1
  #redis配置
  redis:
    host: 192.168.211.132
    port: 6379
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true
